### ISSUE TITLE
doesnt load from SIDE 3

### ISSUE THREAD

**Issue by viktorcech** [seban-slt/simple_cart_dumper#1]
doesnt load from SIDE 3

**Comment by seban-slt** [comment]
"I don't actually own a SIDE3, but firstly, the 'Simple Cart Dumper' relies on BW-DOS, which requires a device compatible with SIO, and SIDE3 lacks support for SIO devices (pseudo-emulation isn't sufficient). While it's possible to run an .XEX file using 'SpartaDOS X' located on SIDE3, it still doesn't make much sense because this software requires a free CARTRIDGE slot into which the CARTRIDGE, you want to dump, needs to be inserted. Additionally, it seems to me that removing SIDE3 from the cartridge slot while the computer is on is not allowed by the manufacturer."

**Comment by seban-slt** [comment]
I don't actually own a SIDE3, but firstly, the 'Simple Cart Dumper' relies on BW-DOS, which requires a device compatible with SIO, and SIDE3 lacks support for SIO devices (pseudo-emulation isn't sufficient). While it's possible to run an .XEX file using 'SpartaDOS X' located on SIDE3, it still doesn't make much sense because this software requires a free CARTRIDGE slot into which the CARTRIDGE, you want to dump, needs to be inserted. Additionally, it seems to me that removing SIDE3 from the cartridge slot while the computer is on is not allowed by the manufacturer.
